### ISSUE TITLE
Using aria-hidden

### ISSUE THREAD

**Issue by svinkle** [komplexb/komplexb.github.io#12]
Regarding "Getting ChromeVox to narrate nicely typically involves strategic placement of aria-hidden", a couple notes from [the spec](http://www.w3.org/TR/wai-aria/states_and_properties#aria-hidden):

> Authors MAY, with caution, use aria-hidden to hide visibly rendered content from assistive technologies only if the act of hiding this content is intended to improve the experience for users of assistive technologies by removing redundant or extraneous content.

Also

> Note: Authors are advised to use extreme caution and consider a wide range of disabilities when hiding visibly rendered content from assistive technologies. For example, a sighted, dexterity-impaired individual may use voice-controlled assistive technologies to access a visual interface.

So for example if a sighted user was trying to click on one of the footnote links using something like [Dragon NaturallySpeaking](http://www.nuance.com/dragon/index.htm) they would not be able to as they're set as hidden.

Just things to keep in mind when encouraging use of `aria-hidden`.

**Comment by komplexb** [comment]
Thanks for the deets. 
What do you make of my use in this context? I really felt like if I closed my eyes and it kept spitting out numbers mid sentence, that it'd throw things off. Seems like there'd be some kind of prejudice against a group with our without the hidden. Unless maybe I add it on hover/focus?
