### ISSUE TITLE
Article fixes

### ISSUE THREAD

**Issue by svinkle** [komplexb/komplexb.github.io#13]
Just somes thing I _think_ should be changed, but I'm not an English major. ;-)

--

> WAI-ARIA and progressive enhancements.

to 

> WAI-ARIA and progressive enhancement.

--

> Recently I decided to change that by

to

> Recently, I decided to change that by

--

> Resolving WAVE’s structural findings was fairly easy, all it took was

to

> Resolving WAVE’s structural findings was fairly easy. All it took was

--

> narrated footnote labels seem out of place when listening to a sentence; sighted readers know that they should skip the superscripted numbers, but the screenreader doesn’t. This was remedied by adding aria-hidden=true to the <a> tags.

to 

> narrated footnote labels seem out of place when listening to a sentence. We can help the sentence flow more naturally by adding aria-hidden=true to the <a> tags.

--

> Accurate voiceover for individual work items.

to 

> Accurate announcement for individual work items.

(VoiceOver is the name of the screen reading for Mac OS X and iOS. I thought this might be confusing.)

--

> By default clicking a `<a>` element

to 

> By default, clicking an `<a>` element

--

> I’ve added the requisite attributes to the`<a>` element

to 

> I’ve added the requisite attributes to the `<a>` element

(space)

**Comment by komplexb** [comment]
good catches, will do.
