### ISSUE TITLE
role="button"

### ISSUE THREAD

**Issue by svinkle** [komplexb/komplexb.github.io#14]
When using `role="button"` on something that's not a `button`, you need to add a keypress event listener for the `space` key. By default, `button` elements fire on `space` as well as `enter`. Keyboard users will expect this.

You could repurpose some of the code from my [a11yclick.js](https://github.com/svinkle/a11yclick/blob/master/a11yclick.js) utility to handle this.

**Comment by komplexb** [comment]
ah i see, will do.
