### ISSUE TITLE
Add some links

### ISSUE THREAD

**Issue by svinkle** [komplexb/komplexb.github.io#15]
Some text in the article I felt could use some links for further reading.

- "ARIA roles and attributes" - Link to something useful, maybe the W3 spec or another helpful guide.
- "relevant documentation" - which are you referring to?
- “progressive enhancement” - https://en.wikipedia.org/wiki/Progressive_enhancement
- "Jekyll" - http://jekyllrb.com/
- "DRY" - https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

**Comment by komplexb** [comment]
i concur, these had crossed my mind, but i figured they might come off as talking down to the audience.

**Comment by komplexb** [comment]
Resolved. Note that 1 link is provided to satisfy bullets 1 and 2.
