### ISSUE TITLE
When using title

### ISSUE THREAD

**Issue by svinkle** [komplexb/komplexb.github.io#2]
Be careful when using `title` attributes. Some screen readers will read them, plus the accessible label/text causing a double announcement. Not really an issue per se, but I'd recommend not using them. 
https://github.com/komplexb/komplexb.github.io/blob/2bd4fd33944c89e3264b827a6c24061602624cc5/index.html#L21

http://www.paciellogroup.com/blog/2012/01/html5-accessibility-chops-title-attribute-use-and-abuse/

**Comment by komplexb** [comment]
I see, sounds similar to extraneous alt-text on images. I'll adjust accordingly.
