### ISSUE TITLE
Home SVG in Safari

### ISSUE THREAD

**Issue by svinkle** [komplexb/komplexb.github.io#3]
The home SVG doesn't appear in Safari on Mac.

https://github.com/komplexb/komplexb.github.io/blob/2bd4fd33944c89e3264b827a6c24061602624cc5/index.html#L22

![image](https://cloud.githubusercontent.com/assets/1392632/9370919/2b84443c-46a2-11e5-93be-9928f1725347.png)

**Comment by komplexb** [comment]
Noticed this... thought it was a weird bug since the same method is used to show the logo in the footer. Not sure where to start on this.
