### ISSUE TITLE
Main nav list

### ISSUE THREAD

**Issue by svinkle** [komplexb/komplexb.github.io#4]
Should probably throw the main nav items in to a `ul` and `display: inline-block` the `li`s, for lists sake.

https://github.com/komplexb/komplexb.github.io/blob/2bd4fd33944c89e3264b827a6c24061602624cc5/index.html#L26

**Comment by komplexb** [comment]
I wondered about this, but felt like wrapping them was sort of extraneous. Does this help the announcements or keyboard nav in a way i'm not aware of?
