### ISSUE TITLE
Footnote anchors

### ISSUE THREAD

**Issue by svinkle** [komplexb/komplexb.github.io#6]
I'm still unsure of why `aria-hidden` was applied to the footnote anchors? Why not keep them available and perhaps add some extra context like `<a href="#fn:1" class="footnote" aria-label="See note on Front-end Developer">1</a>`.

The reason I bring the up is when I run in to the footnote links, it's confusing as where this came from? "It seems like a list of links, ok, but why the footnotes label? What did I miss?"

It's tough because even with these anchors exposed, on click, focus remains where the anchor is, and just continues reading the text. I'm not sure what a good solution may be. Maybe not have them and add the links to the external pages inline, like:
```html
Hi, I'm Byron Buckley, a <a href="http://blog.salsitasoft.com/the-shifting-definition-of-front-end-developer/" target="_blank">Front-end Developer</a>
```

I'll leave it up to you. :)

**Comment by komplexb** [comment]
Yeah its a toughy. I feel like "announcing see note" 5 times, is tough on the flow of the paragraphs. The main point is the content, the footnotes are a secondary feature whose purpose is to complement the main story but not take away from it.
Your suggestion of labeling the footnotes section I think gives a fair balance so the links don't come off as arbitrary. And maybe I could set up the announcement so it refers to footnote context in a meaningful way.

**Comment by komplexb** [comment]
Thinking about it, I did have them inline on a older site, but decided footnotes give me the ability to embelish the reference in a way that doesn't interrupt the narrative.
