### ISSUE TITLE
Footnotes list label

### ISSUE THREAD

**Issue by svinkle** [komplexb/komplexb.github.io#7]
One thing I like doing recently is using `aria-labelledby` for lists of links. It just helps to give a bit of extra context if the person `Tab`s to the links.

https://github.com/komplexb/komplexb.github.io/blob/2bd4fd33944c89e3264b827a6c24061602624cc5/index.html#L109

Example:
```html
<h3 id="footnotes">Footnotes</h3>
  <ol class="footnotelist" aria-labelledby="footnotes">
```

Now when the first link is focused, the screen reader will announce, _"Footnotes, The Shifting Definition of Front-end Developer, link"_.

**Comment by komplexb** [comment]
Nice, will do.
